import localFont from "next/font/local";
import { Sora } from "next/font/google";
import "../styles/globals.scss";

const sora = Sora({ subsets: ["latin"], variable: "--font-sora" });

export const metadata = {
  title: "Next Strapi Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.variable} antialiased font-[family-name:var(--font-sora)]`}>{children}</body>
    </html>
  );
}
